version: "3"
services:
  temp_sensor:
    image: johnkeksex/sensors:latest
    environment:
      - SIM_HOST=localhost
      - SIM_NAME=TEMP1
      - SIM_PERIOD=2
      - SIM_TYPE=temperature
  pressure_sensor:
    image: johnkeksex/sensors:latest
    environment:
      - SIM_HOST=localhost
      - SIM_NAME=PRESS1
      - SIM_PERIOD=2
      - SIM_TYPE=pressure
  current_sensor:
    image: johnkeksex/sensors:latest
    environment:
      - SIM_HOST=localhost
      - SIM_NAME=CUR1
      - SIM_PERIOD=6
      - SIM_TYPE=current
  light_sensor:
    image: johnkeksex/sensors:latest
    environment:
      - SIM_HOST=localhost
      - SIM_NAME=LIGHT1
      - SIM_PERIOD=4
      - SIM_TYPE=light
  temp_second_sensor:
    image: johnkeksex/sensors:latest
    environment:
      - SIM_HOST=localhost
      - SIM_NAME=TEMP2
      - SIM_PERIOD=15
      - SIM_TYPE=temperature
  light_second_sensor:
    image: johnkeksex/sensors:latest
    environment:
      - SIM_HOST=localhost
      - SIM_NAME=LIGHT2
      - SIM_PERIOD=15
      - SIM_TYPE=light