version: "3"

services:
  temp_sensor:
    image: alexandersynex/simulator
    environment:
      - SIM_HOST=192.168.0.104
      - SIM_NAME=TEMPSENS2
      - SIM_PERIOD=2
      - SIM_TYPE=temperature

  temp_low_freq_sensor:
    image: alexandersynex/simulator
    environment:
      - SIM_HOST=192.168.0.104
      - SIM_NAME=TEMPLOWFREQSENS2
      - SIM_PERIOD=10
      - SIM_TYPE=temperature

  pressure_sensor:
    image: alexandersynex/simulator
    environment:
      - SIM_HOST=192.168.0.104
      - SIM_NAME=PRSENS5
      - SIM_PERIOD=5
      - SIM_TYPE=pressure

  current_sensor:
    image: alexandersynex/simulator
    environment:
      - SIM_HOST=192.168.0.104
      - SIM_NAME=CURSENS2
      - SIM_PERIOD=2
      - SIM_TYPE=current

  accel_slow_sensor:
    image: alexandersynex/simulator
    environment:
      - SIM_HOST=192.168.0.104
      - SIM_NAME=ACCELSLOWSENS5
      - SIM_PERIOD=5
      - SIM_TYPE=current

  accel_fast_sensor:
    image: alexandersynex/simulator
    environment:
      - SIM_HOST=192.168.0.104
      - SIM_NAME=ACCELFASTSENS2
      - SIM_PERIOD=2
      - SIM_TYPE=current
    
